export interface Parcel {
  id: string | number;
  trackingNumber: string;
  senderId?: number;
  recipientName: string;
  recipientEmail: string;
  recipientPhone?: string;
  pickupAddress: string;
  pickupLocation?: { lat: number; lng: number } | string | null;
  deliveryAddress: string;
  deliveryLocation?: { lat: number; lng: number } | string | null;
  driverId?: number | null;
  status: 'pending' | 'in_transit' | 'delivered' | 'assigned' | 'pending_pickup';
  currentLat?: number | null;
  currentLng?: number | null;
  currentAddress?: string | null;
  currentLocation?: { lat: number; lng: number } | null;
  weight?: string;
  description?: string;
  deliveredAt?: string | null;
  optimizedRoute?: any;
  routeDistance?: any;
  routeDuration?: any;
  estimatedArrival?: any;
  routePolyline?: any;
  routeInstructions?: any;
  route?: { lat: number; lng: number; timestamp: string }[];
  createdAt: string;
  updatedAt?: string;
}
